### PR TITLE
feat: shield oled 64x48

### PR DESCRIPTION
**Pull request by nothingbutlucas**
Hi there!

Thank u for creating this project is really nice, also really like the code and how you put it together.

So recently I bought the **Wemos D1 Mini** with the **oled shield**. It's a shield with a very tiny screen: **64 x 48**, very cute though.

I added some **basic support** for this screen. I tested it with and without the shield and **works perfectly**.

Apart from the 4 new libraries to handle the screen, I believe that performance should not be affected.

I said *basic support* because the only think that **I add is the display on screen of the serial output**. 

Probably we should change it to make the *face* a little bigger than the text. But well, here is the *MVP*, hope u like it.

output

### CODE REVIEW

**Comment by dj1ch** [comment]
This is pretty cool, I like how it looks and I could get one of these attached to my d1 mini. The only problem here is the serial output, seems like the messages are pretty much taking up a lot of space. If needed we can shorten the status messages so it's more visually appealing to look at on the smaller screen.

**Comment by dj1ch** [comment]
along with that we might need to resolve a small conflict, should be a really quick fix tho

**Comment by nothingbutlucas** [comment]
Great!
Yes, What do you think about making a print of just the face? The truth is that it is quite consistent with the use it already has:
`(X-X)` for errors
`(o-0)` and variations for looking
`(^-^)` for sucessfull proceses
`(>-<)` for starting
`('-')` for printing information or idle

Gonna test it and submit a few more commits

**Comment by dj1ch** [comment]
I fixed the conflict issue, would you be able to open up a new pull request for this? If you want we could just apply this for the entire code base, which may not be necessary but can still be done

**Comment by nothingbutlucas** [comment]
Oh great. Do you prefer a new PR? It's the same for me, I can also add a few commits here and merge this again, whatever u prefer

**Comment by dj1ch** [comment]
> Oh great. Do you prefer a new PR? It's the same for me, I can also add a few commits here and merge this again, whatever u prefer

It doesn't matter really, I was just saying to open up a new PR just in case we were making changes to what was also printed to serial as well as screens

**Pull request merged**
